- samples/Avalonia.Labs.Catalog.Desktop/Program.cs
- samples/Avalonia.Labs.Catalog/Views/AsyncImageView.axaml
- src/Avalonia.Labs.Controls/AsyncImage/AsyncImage.Properties.cs
- src/Avalonia.Labs.Controls/AsyncImage/AsyncImage.cs
- src/Avalonia.Labs.Controls/Cache/CacheBase.cs
- src/Avalonia.Labs.Controls/Cache/CacheOptions.cs
- src/Avalonia.Labs.Controls/Cache/FileCache.cs
- src/Avalonia.Labs.Controls/Cache/ImageCache.cs
- src/Avalonia.Labs.Controls/Cache/InMemoryStorage.cs
- src/Avalonia.Labs.Controls/Cache/InMemoryStorageItem.cs
Imaging caching is supported by a global `ImageCache` singleton, and it's now used by default with AsyncImage. 
Reading from cache can be disabled on an AsyncImage using the `IsCacheEnabled` property.
Fixes #3
> Add caching support to AsyncImage

- samples/Avalonia.Labs.Catalog/Avalonia.Labs.Catalog.csproj
- samples/Avalonia.Labs.Catalog/ViewModels/GestureViewModel.cs
- samples/Avalonia.Labs.Catalog/ViewModels/SwipeViewModel.cs
- samples/Avalonia.Labs.Catalog/Views/GestureContainerView.axaml
- samples/Avalonia.Labs.Catalog/Views/GestureContainerView.axaml.cs
- samples/Avalonia.Labs.Catalog/Views/GestureView.axaml
- samples/Avalonia.Labs.Catalog/Views/GestureView.axaml.cs
- samples/Avalonia.Labs.Catalog/Views/SwipeView.axaml
- samples/Avalonia.Labs.Catalog/Views/SwipeView.axaml.cs
- samples/Avalonia.Labs.Catalog/Views/WelcomeView.axaml
- src/Avalonia.Labs.Controls/Base/MatrixExtensions.cs
- src/Avalonia.Labs.Controls/Base/Pan/PanDirection.cs
- src/Avalonia.Labs.Controls/Base/Pan/PanGestureRecongnizer.cs
- src/Avalonia.Labs.Controls/Base/Pan/PanGestureStatus.cs
- src/Avalonia.Labs.Controls/Base/Pan/PanUpdatedEventArgs.cs
- src/Avalonia.Labs.Controls/Base/PanGestureRecongnizer.cs
- src/Avalonia.Labs.Controls/Base/Tap/TapEventArgs.cs
- src/Avalonia.Labs.Controls/Base/Tap/TapGestureRecognizer.cs
- src/Avalonia.Labs.Controls/SwipeView/Swipe.cs
- src/Avalonia.Labs.Controls/SwipeView/SwipeState.cs
This pull request adds the `` Swipe `` control that works with mobile scrolling as expected. Basically, you can add it and have the ability to swipe left and right to show items under it. Also, it has two new gesture recognizers, `` PanGestureRecognizer `` and `` TapGestureRecognizer ``, which are utilized to make the `` Swipe `` control work.
You can have a look at the demo in the attached video:
https://user-images.githubusercontent.com/5927686/226204800-5de3ca40-076d-4624-8f7b-54c0f7e5ab5f.mp4
> Add swipe component and gesture recognizers

- Directory.Build.props
- samples/Avalonia.Labs.Catalog.Android/Avalonia.Labs.Catalog.Android.csproj
- samples/Avalonia.Labs.Catalog.Android/MainActivity.cs
- samples/Avalonia.Labs.Catalog.Desktop/Avalonia.Labs.Catalog.Desktop.csproj
- samples/Avalonia.Labs.Catalog.Web/Avalonia.Labs.Catalog.Web.csproj
- samples/Avalonia.Labs.Catalog.iOS/Avalonia.Labs.Catalog.iOS.csproj
- samples/Avalonia.Labs.Catalog/Avalonia.Labs.Catalog.csproj
- samples/Avalonia.Labs.Catalog/Views/MainView.axaml.cs
- samples/Avalonia.Labs.Controls.Samples/Avalonia.Labs.Controls.Samples.csproj
Update the samples projects to use avalonia 11.0.4. The library projects are kept on 11.0.0. 
Also fixes https://github.com/AvaloniaUI/Avalonia/issues/13151 by handling UiMode configuration change on the activity.
> Use latest avalonia release in samples, fix android configuration change issue

- src/Avalonia.Labs.Lottie/Lottie.cs
This fixes issue https://github.com/AvaloniaUI/Avalonia.Labs/issues/26 where an exception would occur after the Lottie control is unloaded and then loaded again.
"_animation" and "_customVisual" are now set to null in OnUnloaded. Setting "_animation" to null fixes the exception. Setting "_customVisual" to null allows it to be used as the sole indicator of whether the control is loaded (previously this was being used in combination with "_preloadPath"). The "_preloadPath" variable has been removed as it was unnecessary and could potentially cause issues if the Path property was set multiple times before the control is loaded. Changing the Path property works the same as before. It will load the new animation if the control is already loaded, or return if the control is not loaded. The Path …
> Fix Lottie loading again after unloaded

- samples/Avalonia.Labs.Catalog/Views/SwipeView.axaml
- samples/Avalonia.Labs.Catalog/Views/SwipeView.axaml.cs
- src/Avalonia.Labs.Controls/SwipeView/Swipe.cs
- Updated example of how to close Swipe control from code
- Updated Swipe sample to work with dark theme
- fix
> fix(Swipe): Missing set Visibility of Left and Right container when set SwipeState to Hidden

- samples/Avalonia.Labs.Catalog/ViewModels/FlexItemViewModel.cs
- samples/Avalonia.Labs.Catalog/ViewModels/FlexViewModel.cs
- samples/Avalonia.Labs.Catalog/Views/FlexView.axaml
- src/Avalonia.Labs.Panels/Flex.cs
- src/Avalonia.Labs.Panels/FlexBasis.cs
- src/Avalonia.Labs.Panels/FlexBasisKind.cs
- src/Avalonia.Labs.Panels/FlexPanel.cs
- src/Avalonia.Labs.Panels/Uv.cs
Several enhancements to `FlexPanel`:
1. Fixed implementation of `justify-content` and `align-content` to follow the correct spacing calculation like in HTML. The original implementation was off in case of non-zero row and column gaps. Frankly, all variations looks kinda messy, but one is at least the standardized mess.
2. Fixed implementation of `align-content` in case of items overflowing out of available panel size. In HTML, it falls back to three basic cases.
3. Implemented `flex-shrink` and `flex-grow`. It's a very basic implementation which performs all calculations in the arrange stage. It covers the basic case of stretching items in wrap and no-wrap modes, as well as shrinking in no-wrap mode.
Proper flexbox implementation with fully functional `flex-grow` and `flex-shrink` would …
> FlexPanel enhancements (grow, shrink, basis, fixes)

- src/Avalonia.Labs.Qr/QrCode.cs
Fixes #51 
The original implementation removed 4 bits on every side instead of adding 4 white pixels as a quite zone. This resulted in data loose and broke the QR codes.
1. This PR reversed the logic, repaired the qr data and added an actual quite zone.
2. ~~_Off-topic:_ Should I also add a _bool_ to disable the quite zone? The thickness of the quite zone is depending of bit matrix's size. You get less padding with more data. Maybe the user want to use a fixed `Padding` instead.~~
Added `IsQuietZoneEnabledProperty` to disable the Quiet Zone.
3. This also fixed an issue where `Width` and `Height` changes won't re-render the QRCode. Also also added a cache, so the QRCode data is not re-generated for just layout changes.
> Fixes QuietZone in QR code

- src/Avalonia.Labs.Panels/FlexPanel.cs
fixes #58 
From my (limited) understanding this shouldn't affect any other cases since there is no vertical space left anyways. So the content alignment is essentially irrelevant.
> flexpanel: avoid division by 0

- src/Avalonia.Labs.Controls/Base/Pan/PanGestureRecongnizer.cs
Gestures that track the pointer over multiple moves now need to capture the pointer.
Fixes #63 .
There is an issue with pointers not resetting their capture when released. This is fix in Avalonia master, but not in beta.
> Fix pan gesture losing pointer capture

- src/Avalonia.Labs.Controls/Themes/Controls/AsyncImage.xaml
Adds ClipToBounds=True to AsyncImage's Border to have CornerRadius working properly
> Fix AsyncImage CornerRadius not working

- samples/Avalonia.Labs.Catalog/ViewModels/RouteCommandViewModel.cs
- src/Avalonia.Labs.CommandManager/RoutedCommand.cs
- src/Avalonia.Labs.CommandManager/Utilities/WeakCollection.cs
Fixes: #65 
Depend from https://github.com/AvaloniaUI/Avalonia/pull/15496
Required `11.2.999-cibuild0047796-alpha`
> fix: RoutedCommand CanExecuteChanged Memory Leak

- src/Avalonia.Labs.Panels/FlexPanel.cs
Some of the properties of `FlexPanel` have initial values that don't match the official specification of `FlexBox`. 
[Specification](https://www.w3.org/TR/css-flexbox-1/#property-index)
This caused default behavior of the `FlexPanel` to be inconsistent with `FlexBox` behavior, which it is supposed to be emulating.
- `AlignItems` property: 
- old:   `AlignItems.FlexStart` 
- new: `AlignItems.Stretch`
- `AlignContents` property: 
- old: `AlignContent.FlexStart` 
- new: `AlignContent.Stretch`
- `Wrap` property: 
- old: `FlexWrap.Wrap` 
- new: `FlexWrap.NoWrap`
All new values were taken from the official `FlexBox` [Specification](https://www.w3.org/TR/css-flexbox-1/#property-index).
This is a breaking change with respect to the default behavior of the `FlexPanel` and is likely to cause a …
> Update FlexPanel default property values to match FlexBox specification 

- src/Avalonia.Labs.Panels/AlignContent.cs
- src/Avalonia.Labs.Panels/AlignItems.cs
- src/Avalonia.Labs.Panels/Flex.cs
- src/Avalonia.Labs.Panels/FlexDirection.cs
- src/Avalonia.Labs.Panels/FlexPanel.cs
- src/Avalonia.Labs.Panels/FlexWrap.cs
- src/Avalonia.Labs.Panels/JustifyContent.cs
- resolves https://github.com/Nexus-Mods/NexusMods.App/issues/1754
This adds Docs comments on most `FlexPanel` properties and property enum values.
This should make usage of the panel easier for both developers that are not already familiar with `flexbox`, as well for developers that are.
The [CSS FlexBox Specification](https://www.w3.org/TR/css-flexbox-1//) was used as a starting point for the comments and adapted for `FlexPanel` semantics.
> Add FlexPanel Docs

- src/Avalonia.Labs.Panels/FlexPanel.cs
Fixed a few instances of possible divisions by 0 that caused NaN to propagate until exceptions would occur.
These would happen when available cross axis space was 0 or all child items had 0 main or cross axis size.
Checks were put in place to prevent any potential instance of division by zero, following the [FlexBox specification](https://www.w3.org/TR/css-flexbox-1/) on what behaviour to take in such cases.
See [2fbea8f](https://github.com/AvaloniaUI/Avalonia.Labs/commit/2fbea8f117049e695dd6b90023494d0587807748) for fix details.
Minor refactoring was then done to improve code readability by extracting a few methods from `MeasureOverride` and `ArrangeOverride` and making the logic more concise and explicit.
Minimum code to reproduce the division by 0 issue:
```xml
<Border Height="100"> …
```
> Fix `FlexPanel` division by 0 crashes and cleanup

- src/Avalonia.Labs.Lottie/Lottie.cs
- src/Avalonia.Labs.Lottie/LottieCommand.cs
- src/Avalonia.Labs.Lottie/LottieCompositionCustomVisualHandler.cs
- src/Avalonia.Labs.Lottie/LottiePayload.cs
Hi there! We found the Lottie control really useful to our project, thanks for maintaining it!
For our use case, we needed the ability to pause, resume, and skip through the animation, and also to have callbacks fired when the animation stops or loops.
This adds the following APIs:
* `Start()` and `Stop()` - existing methods, now made public
* `Pause()` and `Resume()` - same as above but retains the current frame
* `SeekToFrame(float frame)` - skip to an exact Lottie frame number
* `SeekToProgress(float progress)` - skip to frame by progress percentage value
* `AutoPlay` - can be used to prevent immediate playback (default `true` so behavior remains compatible)
* `OnAnimationCompleted` and `OnAnimationCompletedRepetition` event handlers - callback on animation stopping at the end, or …
> Lottie playback controls

- samples/Avalonia.Labs.Catalog.Android/Properties/AndroidManifest.xml
- src/Avalonia.Labs.Notifications/Android/NativeNotification.cs
- added missing permission to AndroidManifest.xml
- added "FlagMutable" to native notification, as otherwise a native notification with custom Actions or a Reply Action throws an 
> Java.Lang.IllegalArgumentException:
fixes #97
> #97 - fixing native notifications sample

- src/Avalonia.Labs.Controls/SKCanvasView/SKCanvasView.cs
This PR fixes the `SKCanvasView` not being rendered at 0,0.
Fixes #104
> Fix SKCanvasView render bounds

- src/Avalonia.Labs.Controls/AsyncImage/AsyncImage.cs
If Source is string, create a new URI
Fixes #106 
@grokys could this be related to Bindings refractor? If so, do we want a tracking issue in Avalonia?
> string cannot be auto-converted into URI.

- src/Avalonia.Labs.Gif/GifCompositionCustomVisualHandler.cs
- src/Avalonia.Labs.Gif/GifDrawPayload.cs
- src/Avalonia.Labs.Gif/GifImage.cs
- src/Avalonia.Labs.Gif/GifInstance.cs
Some improvements of PR #108:
1. Unification of `Source` and `SourceStream` properties.
2. Added the ability to load a GIF from uri in string format (e.g. for use in Xaml).
3. Removed an unused `public` constructor from the `internal` class `GifInstance`.
> GifImage improvements

- src/Avalonia.Labs.Notifications/Android/NativeNotificationManager.cs
- src/Avalonia.Labs.Notifications/AppBuilderExtensions.cs
- src/Avalonia.Labs.Notifications/AppNotificationOptions.cs
- src/Avalonia.Labs.Notifications/Apple/AppleNativeNotificationManager.cs
- src/Avalonia.Labs.Notifications/INativeNotification.cs
- src/Avalonia.Labs.Notifications/Linux/LinuxNativeNotificationManager.cs
- src/Avalonia.Labs.Notifications/Windows/NativeNotificationManager.cs
Adds `AppNotificationOptions.ClearOnClose`, defaulting to false, which instructs the notification manager to clear all notification when the app is closed.
Fixes https://github.com/AvaloniaUI/Avalonia.Labs/issues/122
> Add ClearOnClose notification api
